---
title: "BSMM-lab-1"
subtitle: "BSMM 8740 Fall 2023"
author: "Zahra Rohaniasl"
date: "09/18/2023"
format: html
editor: visual
self-contained: true
---

## Setup

Load packages and data:

```{r load-pkg-data}
#| message: false
# install the package 'Lahman'
install.packages('Lahman')
# load the package
library(Lahman)
```

## Exercises

### Exercise 1

```{r glimpse-data}
dplyr::glimpse(Teams)
```

```{r}
?Teams
```

```{r}
dplyr::glimpse(Teams |> head())
```

The `Teams` dataset has \_\_\_ observations and \_\_\_ variables.

### Exercise 2

```{r}
library(magrittr)
mets <- Teams  %>% 
  dplyr::filter(teamID == "NYN")
my_mets <- mets %>% 
  dplyr::filter(yearID %in% 2004:2012) %>%
  dplyr::select(yearID,G,W,L)
my_mets

```

...

### Exercise 3

```{r}
mets_ben <- Teams |>
  dplyr::select(yearID, teamID, G, W, L, RA, RS = R) |>
  dplyr::filter(teamID == "NYN" & yearID %in% 2004:2012)
mets_ben
```

...

```{r}
mets_ben <- mets_ben |>
  dplyr::rename(R = RS)    # new name = old name
mets_ben
```

### Exercise 4

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(WPct = W/G)
mets_ben
```

```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(W_hat = WPct * G)  #The expected number of wins is then equal to the product of the expected winning percentage times the number of games.
mets_ben
```

...

### Exercise 5

...

### Exercise 6
```{r}
dplyr::arrange(mets_ben,desc(WPct))
```

...

### Exercise 7
```{r}
mets_ben %>% 
  dplyr::mutate(Diff = W - W_hat) |>
  dplyr::arrange(desc (Diff))
```

...

### Exercise 8
```{r}

library(dplyr)
mets_ben |>
    dplyr::summarize(
    num_years = n(), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct = sum(WPct), 
    sum_resid = sum(W - W_hat)
  )
```

...

### Exercise 9
```{r}
install.packages("readr")
  library(readr)
IKEA <- read_csv("E:/Zahra-Courses/semester3/Algorithm/github/lab/IKEA.csv")
```
```{r}
head(IKEA)
```
```{r}
library(ggplot2)

ggplot(data = IKEA, aes(x = width, y = price)) +
  geom_point() + 
  labs(
    x = "Width (inches)", 
    y = "Price (USD)", 
    title = "Relationship Between Width and Price of Ikea Furniture"
  )

```

...

### Exercise 10
```{r}
mets_ben <- mets_ben |>
  dplyr::mutate(
    gm = ifelse(
      yearID == 2004, 
      "Duquette", 
      ifelse(
        yearID >= 2011, 
        "Alderson", 
        "Minaya")
    )
  )
```

```{r}
mets_ben <- mets_ben |>
    dplyr::mutate(
    gm = case_when(
      yearID == 2004 ~ "Duquette", 
      yearID >= 2011 ~ "Alderson", 
      TRUE ~ "Minaya"
    )
  )
```
```{r}
mets_ben |>
  group_by(gm) |>
  dplyr::summarize(
    num_years = n(), 
    total_W = sum(W), 
    total_L = sum(L), 
    total_WPct = sum(WPct), 
    sum_resid = sum(W - W_hat)
  ) |>
  arrange(desc(sum_resid))
```
...
